services:
  - type: web
    name: scrapmart
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn Scrapmart.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: your-database-url
      - key: EMAIL_HOST_USER
        value: your-email@example.com
      - key: EMAIL_HOST_PASSWORD
        value: your-email-password
